# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_OS01', '0002_auto_20171009_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_processes', to='VEDA_OS01.Video'),
        ),
    ]
