# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 13:17
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_OS01', '0002_auto_20171016_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='api_key',
            field=fernet_fields.fields.EncryptedTextField(max_length=255, verbose_name=b'API key'),
        ),
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='api_secret',
            field=fernet_fields.fields.EncryptedTextField(max_length=255, verbose_name=b'API secret'),
        ),
    ]
