# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_OS01', '0003_auto_20171019_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mobile_override',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent_ID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='s3_dir',
        ),
        migrations.RemoveField(
            model_name='course',
            name='xue',
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_hold',
            field=models.BooleanField(default=True, help_text=b'Tells whether this course is active.', verbose_name=b'Course Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text=b'Name of this course', max_length=255, verbose_name=b'Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='edx_classid',
            field=models.CharField(help_text=b'Course number to identify the course.', max_length=255, verbose_name=b'Class ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.CharField(help_text=b'Organization of the course.', max_length=50, verbose_name=b'Inst. Code'),
        ),
    ]
