# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-12 19:50
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VEDA_OS01', '0007_auto_20180213_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodeVideosForHlsConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('command_run', models.PositiveIntegerField(default=1)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField(default=0)),
                ('commit', models.BooleanField(default=False, help_text=b'Dry-run or commit.')),
                ('all_videos', models.BooleanField(default=False, help_text=b'Encode all videos for HLS')),
                ('course_ids', models.TextField(blank=True, help_text=b'Whitespace-separated list of course ids for which to re-encode videos.')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
