# Generated by Django 2.2.9 on 2020-01-09 22:56

import VEDA_OS01.models
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_OS01', '0008_encodevideosforhlsconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c24_apikey',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cielo24 API Key'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_fidelity',
            field=models.CharField(choices=[('MECHANICAL', 'Mechanical, 75%'), ('PREMIUM', 'Premium, 95%'), ('PROFESSIONAL', 'Professional, 99%')], default='PROFESSIONAL', max_length=20, verbose_name='Cielo24 Fidelity'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='C24 Turnaround Override'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cielo24Password'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_proc',
            field=models.BooleanField(default=False, verbose_name='Process for Cielo24'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_speed',
            field=models.CharField(choices=[('STANDARD', 'Standard, 48h'), ('PRIORITY', 'Priority, 24h')], default='STANDARD', max_length=20, verbose_name='Cielo24 Turnaround'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c24_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cielo24 Username'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_hold',
            field=models.BooleanField(default=True, help_text='Tells whether this course is active.', verbose_name='Course Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Name of this course', max_length=255, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='edx_classid',
            field=models.CharField(help_text='Course number to identify the course.', max_length=255, verbose_name='Class ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.CharField(help_text='Organization of the course.', max_length=255, verbose_name='Inst. Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_vid_number',
            field=models.IntegerField(default=0, verbose_name='Last Video ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='local_storedir',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='edX Studio URL (VAL)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='previous_statechange',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previous Data Statechange'),
        ),
        migrations.AlterField(
            model_name='course',
            name='proc_loc',
            field=models.BooleanField(default=False, verbose_name='Mediateam Export'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_proc',
            field=models.BooleanField(default=False, verbose_name='Producer Review'),
        ),
        migrations.AlterField(
            model_name='course',
            name='s3_proc',
            field=models.BooleanField(default=True, verbose_name='Process for AWS S3/Mobile?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semesterid',
            field=models.CharField(max_length=4, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sg_projID',
            field=models.IntegerField(default=0, verbose_name='Shotgun Project ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='studio_hex',
            field=models.CharField(default=VEDA_OS01.models._createHex, max_length=50, unique=True, verbose_name='Studio Hex ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tp_apikey',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3Play API Key'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tp_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3Play Password'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tp_proc',
            field=models.BooleanField(default=False, verbose_name='Process for 3Play'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tp_speed',
            field=models.CharField(choices=[('extended_service', '10-Day/Extended'), ('default', '4-Day/Default'), ('expedited_service', '2-Day/Expedited'), ('rush_service', '24 hour/Rush'), ('same_day_service', 'Same Day')], default='default', max_length=20, verbose_name='3Play Turnaround'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tp_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3Play Username'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yt_channel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Youtube Channel ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yt_logon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youtube SFTP U/N'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yt_proc',
            field=models.BooleanField(default=True, verbose_name='Process for Youtube'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_active',
            field=models.BooleanField(default=False, verbose_name='Destination Active'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_nick',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Nickname (3 Char.)'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='encode_bitdepth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Target Bit Depth / Rate Factor'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='encode_filetype',
            field=models.CharField(choices=[('mp4', 'mpeg-4'), ('srt', 'srt file'), ('webm', 'webm'), ('mp3', 'mp3'), ('HLS', 'HLS')], default='mp4', max_length=50, verbose_name='Encode Filetype'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='encode_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Encode Name'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='encode_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Target Resolution (Vert)'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='encode_suffix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Encode Suffix (No underscore)'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='product_spec',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='VAL Profile Name'),
        ),
        migrations.AlterField(
            model_name='encode',
            name='profile_active',
            field=models.BooleanField(default=False, verbose_name='Encode Profile Active'),
        ),
        migrations.AlterField(
            model_name='encodevideosforhlsconfiguration',
            name='all_videos',
            field=models.BooleanField(default=False, help_text='Encode all videos for HLS'),
        ),
        migrations.AlterField(
            model_name='encodevideosforhlsconfiguration',
            name='commit',
            field=models.BooleanField(default=False, help_text='Dry-run or commit.'),
        ),
        migrations.AlterField(
            model_name='encodevideosforhlsconfiguration',
            name='course_ids',
            field=models.TextField(blank=True, help_text='Whitespace-separated list of course ids for which to re-encode videos.'),
        ),
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='api_key',
            field=fernet_fields.fields.EncryptedTextField(max_length=255, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='api_secret',
            field=fernet_fields.fields.EncryptedTextField(max_length=255, verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='org',
            field=models.CharField(help_text='This value must match the value of organization in studio/edx-platform.', max_length=50, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='transcriptcredentials',
            name='provider',
            field=models.CharField(choices=[('3PlayMedia', '3PlayMedia'), ('Cielo24', 'Cielo24')], max_length=50, verbose_name='Transcript provider'),
        ),
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='lang_code',
            field=models.CharField(max_length=50, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='process_id',
            field=models.CharField(max_length=255, verbose_name='Process id'),
        ),
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='provider',
            field=models.CharField(choices=[('3PlayMedia', '3PlayMedia'), ('Cielo24', 'Cielo24')], max_length=50, verbose_name='Transcript provider'),
        ),
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='status',
            field=models.CharField(choices=[('N/A', 'N/A'), ('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('FAILED', 'FAILED'), ('READY', 'READY')], default='PENDING', max_length=50, verbose_name='Transcript status'),
        ),
        migrations.AlterField(
            model_name='transcriptprocessmetadata',
            name='translation_id',
            field=models.CharField(blank=True, help_text='Keeps track of 3Play Translations', max_length=255, null=True, verbose_name='Translation id'),
        ),
        migrations.AlterField(
            model_name='url',
            name='encode_bitdepth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Encoded Avg. Bitdepth'),
        ),
        migrations.AlterField(
            model_name='url',
            name='encode_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration (sec)'),
        ),
        migrations.AlterField(
            model_name='url',
            name='encode_size',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='File Size (bytes)'),
        ),
        migrations.AlterField(
            model_name='url',
            name='encode_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Destination URL'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='URL Updated'),
        ),
        migrations.AlterField(
            model_name='url',
            name='val_input',
            field=models.BooleanField(default=False, verbose_name='Inputted to EDX-VAL?'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='client_information',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Client Information Field'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment/Info'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='edx_id',
            field=models.CharField(max_length=20, verbose_name='VEDA Video ID'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='edx_studio_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='edX Studio URL (VAL)'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='file_complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='file_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='final_report',
            field=models.BooleanField(default=False, verbose_name='Reported'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='status_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Target Email'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upload Datetime'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='upload_filename',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Video (Client) Title'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='video_serial',
            field=models.CharField(max_length=20, verbose_name='Upload Process Serial'),
        ),
        migrations.AlterField(
            model_name='vedaupload',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Youtube ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='abvid_serial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VEDA Upload Process Serial'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cielo24_fidelity',
            field=models.CharField(blank=True, choices=[('MECHANICAL', 'Mechanical, 75% Accuracy'), ('PREMIUM', 'Premium, 95% Accuracy'), ('PROFESSIONAL', 'Professional, 99% Accuracy')], max_length=20, null=True, verbose_name='Cielo24 Fidelity'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cielo24_turnaround',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard, 48h'), ('PRIORITY', 'Priority, 24h')], max_length=20, null=True, verbose_name='Cielo24 Turnaround'),
        ),
        migrations.AlterField(
            model_name='video',
            name='client_title',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Video (Client) Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='edx_id',
            field=models.TextField(verbose_name='VEDA Video ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='process_transcription',
            field=models.BooleanField(default=False, verbose_name='Process transcripts from Cielo24/3PlayMedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='provider',
            field=models.CharField(blank=True, choices=[('3PlayMedia', '3PlayMedia'), ('Cielo24', 'Cielo24')], max_length=20, null=True, verbose_name='Transcription provider'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_language',
            field=models.CharField(blank=True, help_text='This is video speech language.', max_length=50, null=True, verbose_name='video source language'),
        ),
        migrations.AlterField(
            model_name='video',
            name='stat_queuetime',
            field=models.FloatField(default=0, verbose_name='Video Avg. Queuetime (sec)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='studio_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Studio Upload ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='three_play_turnaround',
            field=models.CharField(blank=True, choices=[('extended', '10-Day/Extended'), ('standard', '4-Day/Standard'), ('expedited', '2-Day/Expedited'), ('rush', '24 hour/Rush'), ('same_day', 'Same Day'), ('two_hour', '2 Hour')], max_length=20, null=True, verbose_name='3PlayMedia Turnaround'),
        ),
        migrations.AlterField(
            model_name='video',
            name='transcript_status',
            field=models.CharField(choices=[('N/A', 'N/A'), ('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('FAILED', 'FAILED'), ('READY', 'READY')], default='N/A', max_length=100, verbose_name='Transcription Status'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_active',
            field=models.BooleanField(default=True, verbose_name='Video Active?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_glacierid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Glacier Archive ID String'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_orig_bitrate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Orig. Bitrate'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_orig_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration (Original)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_orig_extension',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Orig. File Extension'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_orig_filesize',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Master Filesize'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_orig_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orig. Resolution'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_trans_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Process Complete'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_trans_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Process Start'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_trans_status',
            field=models.CharField(choices=[('Ingest', 'System Ingest'), ('Transcode Queue', 'Transcode Queue'), ('Active Transcode', 'Active Transcode'), ('Transcode Retry', 'Transcode Retry'), ('Transcode Complete', 'Transcode Complete'), ('Deliverable Upload', 'Deliverable Upload'), ('File Complete', 'File Complete'), ('Transcode Error', 'Transcode Error'), ('Corrupt File', 'Corrupt File on Ingest'), ('Review Hold', 'Review Hold'), ('Review Reject', 'Review Rejected'), ('Final Publish', 'Review to Final Publish'), ('Youtube Duplicate', 'Youtube Duplicate'), ('Queue', 'In Encode Queue'), ('Progress', 'In Progress'), ('Complete', 'Complete')], default='Ingest', max_length=100, verbose_name='Transcode Status'),
        ),
    ]
